<?php

namespace App\Services;

class KhqrHelper
{
    /**
     * Appends an expiration timestamp to an EMVCo KHQR string
     * and recalculates the CRC16 checksum.
     *
     * @param string $qrString The raw QR string generated by BakongKHQR
     * @param int $validSeconds Validity period in seconds (e.g., 900 for 15 mins)
     * @return string
     */
    public static function attachDynamicExpiry(string $qrString, int $validSeconds = 900): string
    {
        // 1. Remove the last 4 characters (CRC16 value) and Tag '6304'
        // Standard EMVCo ends with '6304XXXX'
        if (substr($qrString, -8, 4) === '6304') {
            $baseQr = substr($qrString, 0, -8);
        } else {
            return $qrString;
        }

        // 2. Bakong dynamic expiration timestamp in milliseconds (13 digits)
        $expiryTimestamp = (string) ((time() + $validSeconds) * 1000);
        
        // Tag 58 (Timestamp tag in EMVCo for Bakong dynamic QR)
        // Sub-tag or root Tag: 58 + length + timestamp
        $tag = '58';
        $len = str_pad((string) strlen($expiryTimestamp), 2, '0', STR_PAD_LEFT);
        $expiryPayload = $tag . $len . $expiryTimestamp;

        // 3. Append expiry tag before the CRC tag
        $payloadWithExpiry = $baseQr . $expiryPayload . '6304';

        // 4. Calculate new CRC16 (CCITT-FALSE: poly 0x1021, init 0xFFFF)
        $crc = self::calculateCRC16($payloadWithExpiry);

        return $payloadWithExpiry . $crc;
    }

    /**
     * Calculates EMVCo standard CRC16-CCITT (0xFFFF)
     */
    public static function calculateCRC16(string $data): string
    {
        $crc = 0xFFFF;
        $len = strlen($data);

        for ($i = 0; $i < $len; $i++) {
            $crc ^= (ord($data[$i]) << 8);
            for ($j = 0; $j < 8; $j++) {
                if (($crc & 0x8000) !== 0) {
                    $crc = (($crc << 1) ^ 0x1021) & 0xFFFF;
                } else {
                    $crc = ($crc << 1) & 0xFFFF;
                }
            }
        }

        return strtoupper(str_pad(dechex($crc), 4, '0', STR_PAD_LEFT));
    }
}